# This file was generated by GoReleaser. DO NOT EDIT.
cask "rmesh" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "03eec6fb7948158c76cba4fc06b88013831501e312a551dad1405d792ef9cbb6"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b8708e03a2f26e61525df1702a327bfdfbf79eacd61fa60b2914065b861ca1d3"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "910d28c67a38d38aec30f10df675416715b6e0f51c70b0f6f60e0d7e365c19fa"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5a11c3b0387ad9481c01a614d1af90470156a5c6c532bf1c8b5d75a2bdf5f17"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rmesh"
  desc "Command-line tool for RelayMesh"
  homepage "https://github.com/relaymonkey/rmesh-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rmesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rmesh"]
    end
  end
  generate_completions_from_executable "rmesh",
    shell_parameter_format: :cobra

  # No zap stanza required

  caveats <<~EOS
    Shell tab completion (optional):

      eval "$(rmesh completion zsh)"

    Dynamic completion requires rmesh auth login.
  EOS
end
