# This file was generated by GoReleaser. DO NOT EDIT.
cask "rmesh" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "0177277b70af1cba01fd34d7030522139492eb8466cdea9e1148800ec8e8a088"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0679e40ff6dee0d576c0f3e603a7f597afbfc95384ea320f96ab4eac93583128"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "618e2f388d2649a2dcc79838916b427c9f19e09be20d6790d4f8183854ceee97"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "489f5f3d5ecd9f0415b9ff15734542175502c85ba1e1e1803227f59f3a29ac55"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rmesh"
  desc "Command-line tool for RelayMesh"
  homepage "https://github.com/relaymonkey/rmesh-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rmesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rmesh"]
    end
  end
  generate_completions_from_executable "rmesh",
    shell_parameter_format: :cobra

  # No zap stanza required

  caveats <<~EOS
    Shell tab completion (optional):

      eval "$(rmesh completion zsh)"

    Dynamic completion requires rmesh auth login.
  EOS
end
