# This file was generated by GoReleaser. DO NOT EDIT.
cask "rmesh" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c0a5f9fa22824d2fd51c2253685aabb8632d083983c531abdffbf99161e786fd"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "071e1531403a13f786920a064132f6d280e4df8e882a60931f0b838d4e359cc7"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb3eb4c01e6197eab9955c9790240e288714d0bdf4503fa7d41f38413548523b"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aaef3186eea9b278d40d8f287bbe3d099f9b49b7208fa7b3e5a359cc956ae851"
      url "https://github.com/relaymonkey/rmesh-cli/releases/download/v#{version}/rmesh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rmesh"
  desc "Command-line tool for RelayMesh"
  homepage "https://github.com/relaymonkey/rmesh-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rmesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rmesh"]
    end
  end
  generate_completions_from_executable "rmesh",
    shell_parameter_format: :cobra

  # No zap stanza required

  caveats <<~EOS
    Shell tab completion (optional):

      eval "$(rmesh completion zsh)"

    Dynamic completion requires rmesh auth login.
  EOS
end
